### ISSUE TITLE
Lunch preferences

### ISSUE THREAD

**Issue by yakovb** [CameronD17/whereshouldweb3goforlunch#1]
Could you please include the following lunch destinations and weightings:

Blue Bird: 25
Anima: 15
Tesco: 9
Lidl: 9
Digorgio: 7
Blue Bear: 7
Sully's: 5
Coro: 5
Lezzetli: 5
Margiotta: 5
Water of Leith: 4
New Town Deli: 2
Downstairs: 1
Coffee Angel: 1

**Comment by CameronD17** [comment]
No
